# Generated by Django 3.0.8 on 2020-08-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_students_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='stu_count',
            field=models.IntegerField(default=0),
        ),
    ]
