# Generated by Django 3.0.8 on 2020-08-15 14:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0002_user_dob'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('objecs', django.db.models.manager.Manager()),
            ],
        ),
    ]
