# Generated by Django 3.0.8 on 2020-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0003_auto_20200815_1459'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
